name = "C25Challenge"
uuid = "ad2139e0-77b1-4db9-80cd-0422f1648733"
authors = ["Will Seiple <60242249+willseiple@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
HashCode2014 = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"

[compat]
HashCode2014 = "0.1.0"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
